name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install stable
      run: rustup toolchain install stable

    - name: Build
      run: cargo build --all

    - name: Run tests
      run: cargo test --all

    - name: Run tests with all features
      run: cargo test --all-features
